### PR TITLE
Added link to lopper demo

### PR DESCRIPTION
**Pull request by tammyleino**
Linked lopper repo and demo into documentation.
Signed-off-by: Tammy Leino <tammy_leino@mentor.com>

### CODE REVIEW

**Comment by arnopo** [comment]
Could you rebase the PR? I did it using github but I'm not a fan of the way he did it...

**Review by TanmayShah-xilinx — APPROVED** [review]

**Comment by wmamills** [comment]
The real content of this PR was added by PR#10
This PR should be closed.

I am sure it was helpful to Dan when he was authoring his PR

**Comment by tammyleino** [comment]
> The real content of this PR was added by PR#10. The merge base for this PR is still messed up. This should be a single commit. not 3. This PR should be closed.
> 
> I am sure it was helpful to Dan when he was authoring his PR

@wmamills I do not see where Dan's is a duplicate.  This PR is adding the lopper demo to index.rst, which I volunteered to do for Bruce.  It is not in main already.  Maybe you are seeing that I had to merge Dan's changes into my PR before merging.

**Comment by wmamills** [comment]
@tammyleino sorry, I was mixing up the two demos.
The comments about the base are still valid I think.  I see 3 different commits here but only the last one is what we want.
If it is OK with you I will redo this and cherry pick your commit onto a new PR

**Comment by wmamills** [comment]
I have replaced this PR with PR#12

**Pull request closed without merging**
